version: 0.0
os: linux
files:
  - source: /
    destination: pyapp
hooks:
  BeforeInstall:
    - location: pyapp/install_dependences.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: pyapp/install.sh
      timeout: 300
      runas: root